---
# Configure RabbitMQ for cluster

- name: gather rabbitmq hosts
  set_fact:
    rabbitmq_hosts_fact: "{{ rabbitmq_hosts_fact|default([]) + [{'host': hostvars[item]['ansible_hostname'], 'ip': hostvars[item]['ansible_default_ipv4']['address']}] }}"
  when: rabbitmq_hosts is not defined or not rabbitmq_hosts
  with_items: "{{ groups['rabbit'] }}"

- name: ensure hostnames are in the host file
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.host }}"
  with_items: "{{ rabbitmq_hosts_fact|default(rabbitmq_hosts) }}"

- name: backup old erlang cookie
  shell: cp -a /var/lib/rabbitmq/.erlang.cookie /var/lib/rabbitmq/.erlang.cookie.old
  changed_when: false

- name: check if erlang cookie changed and if it is so stopping server
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie.old
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
  notify:
    stop rabbitmq-server

- meta: flush_handlers

- name: updating rabbitmq erlang cookie
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400

- name: remove old erlang cookie
  file:
    path: /var/lib/rabbitmq/.erlang.cookie.old
    state: absent
  changed_when: false
