---

- include: repository.yml
  tags: repository
  when: rabbitmq_use_repository

- include: packages.yml
  tags: packages
  when: rabbitmq_use_repository

- include: config-cluster.yml
  when: rabbitmq_create_cluster

- include: config.yml

- include: service.yml

- include: cluster.yml
  when: (rabbitmq_create_cluster == true) and (ansible_fqdn != rabbitmq_cluster_master) and (inventory_hostname != rabbitmq_cluster_master)

- include: rabbitmq.yml
  when: 'not rabbitmq_create_cluster or (ansible_fqdn == rabbitmq_cluster_master) or (inventory_hostname == rabbitmq_cluster_master)'

- meta: flush_handlers
